"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useSyncExternalStore,
  type ReactNode,
} from "react";

export type Locale = "en" | "ar";

type Dict = Record<string, string>;

const en: Dict = {
  "brand.name": "Tanoor Al Jazeera",
  "brand.sub": "Industrial Factory",
  "brand.badge": "HR Management System",
  "hero.eyebrow": "Saudi-Compliant",
  "hero.title": "Complete HR Management,",
  "hero.desc":
    "A unified platform for employees, attendance, payroll, documents, recruitment and KPIs — integrated with Absher, MODON, Qiwa and Mudad.",
  "features.title": "01",
  "features.subtitle": "Core Modules",
  "feature.1": "Employee Management",
  "feature.2": "Payroll & Attendance",
  "feature.3": "Document Expiry",
  "feature.4": "KPI Tracking",
  "portals.title": "Government Portals",
  "portal.absher": "Absher",
  "portal.qiwa": "Qiwa",
  "portal.modon": "MODON",
  "portal.mudad": "Mudad",
  "footer.copy": "© 2025 Tanoor Al Jazeera",
  "footer.compliance": "Saudi-compliant",
  "lang.toggle": "عربي",
  "lang.toggle.en": "English",
  "login.title": "Welcome back",
  "login.subtitle": "Sign in to access the HR dashboard",
  "login.username": "Username",
  "login.username.ph": "Enter username",
  "login.password": "Password",
  "login.password.ph": "Enter password",
  "login.remember": "Remember me",
  "login.forgot": "Forgot password?",
  "login.submit": "Sign In",
  "login.submitting": "Signing in…",
  "login.support":
    "For an account or to recover your password, contact the system administrator at",
  "login.secured": "Secured by Tanoor Al Jazeera HR System",
  "login.admin": "Admin",
  "login.err.required": "Please enter your username and password.",
  "login.err.invalid": "Invalid username or password.",
  "login.success": "Welcome back! Redirecting to your dashboard…",
  "forgot.title": "Reset Password",
  "forgot.desc":
    "Enter your username and we will send reset instructions to the registered email.",
  "forgot.username": "Username",
  "forgot.username.ph": "Enter your username",
  "forgot.submit": "Send Reset Link",
  "forgot.submitting": "Sending…",
  "forgot.cancel": "Back to sign in",
  "forgot.success":
    "If the username exists, reset instructions have been sent to the registered email.",
  "forgot.back": "Back to login",
  "show": "Show",
  "hide": "Hide",
  "demo.hint": "Demo: admin / tanoor2025",

  /* ====== Dashboard nav ====== */
  "nav.company": "Company Overview",
  "nav.employees": "Employees",
  "nav.attendance": "Attendance",
  "nav.leave": "Leave Management",
  "nav.payroll": "Payroll",
  "nav.documents": "Documents",
  "nav.recruitment": "Recruitment",
  "nav.kpi": "KPI Tracking",
  "nav.reports": "Reports",
  "nav.group.hr": "Human Resources",
  "nav.group.ops": "Operations",
  "nav.group.system": "System",
  "nav.signout": "Sign Out",
  "nav.profile": "Profile",

  /* ====== Dashboard shared ====== */
  "dash.welcome": "Welcome back",
  "dash.search": "Search…",
  "dash.search.placeholder": "Search by name, ID, or phone…",
  "dash.filters": "Filters",
  "dash.department": "Department",
  "dash.status": "Status",
  "dash.type": "Type",
  "dash.nationality": "Nationality",
  "dash.month": "Month",
  "dash.period": "Period",
  "dash.all": "All",
  "dash.add": "Add",
  "dash.addNew": "Add New",
  "dash.edit": "Edit",
  "dash.delete": "Delete",
  "dash.save": "Save",
  "dash.cancel": "Cancel",
  "dash.confirm": "Confirm",
  "dash.confirmDelete": "Confirm Delete",
  "dash.confirmDeleteMsg": "Are you sure you want to delete this record? This action cannot be undone.",
  "dash.actions": "Actions",
  "dash.view": "View",
  "dash.export": "Export",
  "dash.import": "Import",
  "dash.loading": "Loading…",
  "dash.noData": "No data found",
  "dash.noDataDesc": "Try adjusting your filters or add a new record.",
  "dash.error": "Something went wrong",
  "dash.retry": "Try Again",
  "dash.created": "Created successfully",
  "dash.updated": "Updated successfully",
  "dash.deleted": "Deleted successfully",
  "dash.saved": "Saved successfully",
  "dash.approved": "Leave approved",
  "dash.rejected": "Leave rejected",
  "dash.exported": "Exported successfully",

  /* ====== Company overview page ====== */
  "company.title": "Company Overview",
  "company.subtitle": "Real-time insights across your workforce",
  "company.totalEmployees": "Total Employees",
  "company.activeEmployees": "Active Employees",
  "company.saudization": "Saudization Rate",
  "company.monthlyPayroll": "Monthly Payroll",
  "company.pendingLeaves": "Pending Leaves",
  "company.avgKpi": "Avg KPI Score",
  "company.candidates": "Open Candidates",
  "company.byDept": "Employees by Department",
  "company.byVisa": "Workforce by Visa Type",
  "company.deptSalary": "Avg Salary by Department",
  "company.payrollTrend": "Payroll Trend (3 months)",
  "company.profile": "Company Profile",
  "company.name": "Tanoor Al Jazeera Industrial Factory",
  "company.address": "Industrial City, Dammam, Eastern Province, Saudi Arabia",
  "company.cr": "Commercial Registration",
  "company.vat": "VAT Number",
  "company.gosi": "GOSI Establishment",
  "company.established": "Established",
  "company.employees": "Employees",
  "company.departments": "Departments",

  /* ====== Employees page ====== */
  "emp.title": "Employees",
  "emp.subtitle": "Manage your workforce records",
  "emp.cardView": "Cards",
  "emp.tableView": "Table",
  "emp.empNo": "Emp No",
  "emp.name": "Full Name",
  "emp.nameAr": "Arabic Name",
  "emp.job": "Job Title",
  "emp.dept": "Department",
  "emp.salary": "Salary",
  "emp.contact": "Contact",
  "emp.hireDate": "Hire Date",
  "emp.nationality": "Nationality",
  "emp.gender": "Gender",
  "emp.male": "Male",
  "emp.female": "Female",
  "emp.dob": "Date of Birth",
  "emp.marital": "Marital Status",
  "emp.married": "Married",
  "emp.single": "Single",
  "emp.divorced": "Divorced",
  "emp.widowed": "Widowed",
  "emp.phone": "Phone",
  "emp.email": "Email",
  "emp.address": "Address",
  "emp.emergency": "Emergency Contact",
  "emp.employmentType": "Employment Type",
  "emp.fullTime": "Full Time",
  "emp.partTime": "Part Time",
  "emp.contract": "Contract Type",
  "emp.contractEnd": "Contract End",
  "emp.basicSalary": "Basic Salary",
  "emp.allowances": "Allowances",
  "emp.bank": "Bank Account",
  "emp.iban": "IBAN",
  "emp.passport": "Passport",
  "emp.passportNo": "Passport No",
  "emp.passportExpiry": "Passport Expiry",
  "emp.iqama": "Iqama",
  "emp.iqamaNo": "Iqama/National ID No",
  "emp.iqamaExpiry": "Iqama/ID Expiry",
  "emp.visa": "Visa Type",
  "emp.profilePhoto": "Profile Photo",
  "emp.iqamaPhoto": "Iqama Photo",
  "emp.passportPhoto": "Passport Photo",
  "emp.notes": "Notes",
  "emp.uploadPhoto": "Upload Photo",
  "emp.extractIqama": "Extract from Iqama",
  "emp.extractPassport": "Extract from Passport",
  "emp.extracting": "Extracting…",
  "emp.extracted": "Document data extracted",
  "emp.extractFailed": "Could not extract data — please fill manually",
  "emp.addEmployee": "Add Employee",
  "emp.editEmployee": "Edit Employee",
  "emp.importCsv": "Import Excel",
  "emp.exportXlsx": "Export to Excel",
  "emp.total": "Total Employees",
  "emp.active": "Active",
  "emp.onLeave": "On Leave",
  "emp.saudi": "Saudi Nationals",
  "emp.viewDetails": "View Details",
  "emp.section.personal": "Personal",
  "emp.section.employment": "Employment",
  "emp.section.legal": "Legal Documents",
  "emp.section.financial": "Financial",
  "emp.section.photos": "Photos & Documents",

  /* ====== Attendance ====== */
  "att.title": "Attendance",
  "att.subtitle": "Track daily check-in and check-out",
  "att.date": "Date",
  "att.checkIn": "Check In",
  "att.checkOut": "Check Out",
  "att.workHours": "Work Hours",
  "att.overtime": "Overtime (h)",
  "att.present": "Present",
  "att.late": "Late",
  "att.absent": "Absent",
  "att.leave": "On Leave",
  "att.holiday": "Holiday",
  "att.add": "Add Attendance",
  "att.total": "Total Records",
  "att.presentCount": "Present",
  "att.lateCount": "Late Arrivals",
  "att.leaveCount": "On Leave",

  /* ====== Leave ====== */
  "leave.title": "Leave Management",
  "leave.subtitle": "Approve and track employee leave",
  "leave.type": "Leave Type",
  "leave.annual": "Annual",
  "leave.sick": "Sick",
  "leave.emergency": "Emergency",
  "leave.unpaid": "Unpaid",
  "leave.maternity": "Maternity",
  "leave.startDate": "Start Date",
  "leave.endDate": "End Date",
  "leave.days": "Days",
  "leave.reason": "Reason",
  "leave.approver": "Approver",
  "leave.pending": "Pending",
  "leave.approved": "Approved",
  "leave.rejected": "Rejected",
  "leave.apply": "Apply Leave",
  "leave.approve": "Approve",
  "leave.reject": "Reject",
  "leave.balance": "Leave Balance",
  "leave.totalRequests": "Total Requests",
  "leave.pendingBalance": "Pending Review",
  "leave.approvedBalance": "Approved Days",

  /* ====== Payroll ====== */
  "pay.title": "Payroll",
  "pay.subtitle": "Salaries, deductions, and GOSI contributions",
  "pay.month": "Month",
  "pay.basic": "Basic Salary",
  "pay.allowances": "Allowances",
  "pay.overtime": "Overtime",
  "pay.deductions": "Deductions",
  "pay.gosi": "GOSI",
  "pay.net": "Net Salary",
  "pay.payDate": "Pay Date",
  "pay.run": "Run Payroll",
  "pay.runConfirm": "Run payroll for {month}? This will overwrite any existing records for that month.",
  "pay.runSuccess": "Payroll processed for {month} ({count} employees)",
  "pay.runLoading": "Processing payroll…",
  "pay.payslip": "Payslip",
  "pay.total": "Total Net Salary",
  "pay.totalGosi": "Total GOSI",
  "pay.totalOvertime": "Total Overtime",
  "pay.employees": "Employees Paid",
  "pay.byMonth": "Net Salary by Month",
  "pay.processed": "Processed",
  "pay.paid": "Paid",
  "pay.employee": "Employee",
  "pay.gosiNote": "GOSI: Saudi 9.75% · Expat 2%",

  /* ====== Documents ====== */
  "doc.title": "Documents",
  "doc.subtitle": "Track expiry of legal and contract documents",
  "doc.docType": "Document Type",
  "doc.iqama": "Iqama",
  "doc.passport": "Passport",
  "doc.contract": "Contract",
  "doc.certificate": "Certificate",
  "doc.other": "Other",
  "doc.title2": "Title",
  "doc.issueDate": "Issue Date",
  "doc.expiryDate": "Expiry Date",
  "doc.file": "File",
  "doc.upload": "Upload Document",
  "doc.add": "Add Document",
  "doc.valid": "Valid",
  "doc.expiring": "Expiring Soon",
  "doc.expired": "Expired",
  "doc.total": "Total Documents",
  "doc.expiringSoon": "Expiring (≤30 days)",
  "doc.expiredCount": "Expired",
  "doc.alertTitle": "Expiry Alerts",

  /* ====== Recruitment ====== */
  "rec.title": "Recruitment",
  "rec.subtitle": "Track candidates through your hiring pipeline",
  "rec.position": "Position",
  "rec.source": "Source",
  "rec.experience": "Experience (yrs)",
  "rec.rating": "Rating",
  "rec.expectedSalary": "Expected Salary",
  "rec.appliedAt": "Applied At",
  "rec.add": "Add Candidate",
  "rec.applied": "Applied",
  "rec.screening": "Screening",
  "rec.interview": "Interview",
  "rec.offered": "Offered",
  "rec.hired": "Hired",
  "rec.rejected": "Rejected",
  "rec.total": "Total Candidates",
  "rec.inPipeline": "In Pipeline",
  "rec.interviewing": "Interviewing",
  "rec.offeredCount": "Offers Extended",

  /* ====== KPI ====== */
  "kpi.title": "KPI Tracking",
  "kpi.subtitle": "Performance metrics per employee",
  "kpi.productivity": "Productivity",
  "kpi.quality": "Quality",
  "kpi.teamwork": "Teamwork",
  "kpi.punctuality": "Punctuality",
  "kpi.initiative": "Initiative",
  "kpi.finalScore": "Final Score",
  "kpi.comments": "Comments",
  "kpi.add": "Add KPI",
  "kpi.edit": "Edit KPI",
  "kpi.distribution": "Score Distribution",
  "kpi.avgScore": "Average Score",
  "kpi.topCount": "Top Performers (≥85)",
  "kpi.lowCount": "Need Improvement (<70)",
  "kpi.total": "Total Reviews",
  "kpi.excellent": "Excellent",
  "kpi.good": "Good",
  "kpi.average": "Average",
  "kpi.poor": "Poor",

  /* ====== Reports ====== */
  "rep.title": "Reports & Analytics",
  "rep.subtitle": "Saudi-compliant HR analytics & exports",
  "rep.saudization": "Saudization Report",
  "rep.saudi": "Saudi Nationals",
  "rep.expat": "Expat Workers",
  "rep.rate": "Saudization Rate",
  "rep.target": "Target (Nitaqat)",
  "rep.deptBreakdown": "Department Breakdown",
  "rep.payrollByMonth": "Payroll by Month",
  "rep.attendanceTrend": "Attendance (7 days)",
  "rep.kpiByDept": "Avg KPI by Department",
  "rep.exportAllEmp": "Export All Employees",
  "rep.exportFull": "Export Full Report",
  "rep.summary": "Executive Summary",

  /* ====== Footer ====== */
  "footer.rights": "All rights reserved.",
  "footer.ai": "AI Assistant",
  "footer.poweredBy": "Powered by",

  /* ====== AI Assistant ====== */
  "ai.title": "AI Assistant",
  "ai.subtitle": "Ask about your HR data",
  "ai.placeholder": "Ask anything about employees, payroll, leave…",
  "ai.send": "Send",
  "ai.thinking": "Thinking…",
  "ai.welcome": "Hello! I'm your HR assistant. I can answer questions about employees, attendance, payroll, leave, documents, recruitment, and KPIs. Try asking:\n• How many employees do we have?\n• What is our Saudization rate?\n• How many pending leave requests?",
  "ai.disclaimer": "AI-generated responses use real-time database data. Verify critical decisions.",

  /* ====== Employee detail ====== */
  "det.profile": "Profile",
  "det.employment": "Employment",
  "det.documents": "Documents",
  "det.attendance": "Attendance",
  "det.leave": "Leave",
  "det.payroll": "Payroll",
  "det.kpis": "KPIs",
  "det.personalInfo": "Personal Information",
  "det.contactInfo": "Contact Information",
  "det.employmentInfo": "Employment Information",
  "det.financialInfo": "Financial Information",
  "det.legalDocs": "Legal Documents",
  "det.noRecords": "No records found",
  "det.totalSalary": "Total Salary",
  "det.years": "years",
  "det.days": "days",
};

const ar: Dict = {
  "brand.name": "تنور الجزيرة",
  "brand.sub": "المصنع الصناعي",
  "brand.badge": "نظام إدارة الموارد البشرية",
  "hero.eyebrow": "متوافق مع الأنظمة السعودية",
  "hero.title": "إدارة موارد بشرية متكاملة،",
  "hero.desc":
    "منصة موحدة للموظفين والحضور والرواتب والمستندات والتوظيف ومؤشرات الأداء — متكاملة مع أبشر ومدن وقوى ومُدد.",
  "features.title": "01",
  "features.subtitle": "الوحدات الأساسية",
  "feature.1": "إدارة الموظفين",
  "feature.2": "الرواتب والحضور",
  "feature.3": "انتهاء المستندات",
  "feature.4": "تتبع مؤشرات الأداء",
  "portals.title": "البوابات الحكومية",
  "portal.absher": "أبشر",
  "portal.qiwa": "قوى",
  "portal.modon": "مُدن",
  "portal.mudad": "مُدد",
  "footer.copy": "© 2025 تنور الجزيرة",
  "footer.compliance": "متوافق سعوديًا",
  "lang.toggle": "English",
  "lang.toggle.en": "English",
  "login.title": "مرحبًا بعودتك",
  "login.subtitle": "سجّل الدخول للوصول إلى لوحة الموارد البشرية",
  "login.username": "اسم المستخدم",
  "login.username.ph": "أدخل اسم المستخدم",
  "login.password": "كلمة المرور",
  "login.password.ph": "أدخل كلمة المرور",
  "login.remember": "تذكّرني",
  "login.forgot": "نسيت كلمة المرور؟",
  "login.submit": "تسجيل الدخول",
  "login.submitting": "جارٍ تسجيل الدخول…",
  "login.support":
    "للحصول على حساب أو لاستعادة كلمة المرور، تواصل مع مسؤول النظام على",
  "login.secured": "محمي بواسطة نظام تنور الجزيرة للموارد البشرية",
  "login.admin": "المسؤول",
  "login.err.required": "يرجى إدخال اسم المستخدم وكلمة المرور.",
  "login.err.invalid": "اسم المستخدم أو كلمة المرور غير صحيحة.",
  "login.success": "مرحبًا بعودتك! جارٍ تحويلك إلى لوحة التحكم…",
  "forgot.title": "استعادة كلمة المرور",
  "forgot.desc":
    "أدخل اسم المستخدم وسنرسل تعليمات الاستعادة إلى البريد الإلكتروني المسجّل.",
  "forgot.username": "اسم المستخدم",
  "forgot.username.ph": "أدخل اسم المستخدم",
  "forgot.submit": "إرسال رابط الاستعادة",
  "forgot.submitting": "جارٍ الإرسال…",
  "forgot.cancel": "العودة لتسجيل الدخول",
  "forgot.success":
    "إذا كان اسم المستخدم موجودًا، فقد تم إرسال تعليمات الاستعادة إلى البريد المسجّل.",
  "forgot.back": "العودة لتسجيل الدخول",
  "show": "إظهار",
  "hide": "إخفاء",
  "demo.hint": "تجريبي: admin / tanoor2025",

  /* ====== Dashboard nav ====== */
  "nav.company": "نظرة عامة",
  "nav.employees": "الموظفون",
  "nav.attendance": "الحضور",
  "nav.leave": "إدارة الإجازات",
  "nav.payroll": "الرواتب",
  "nav.documents": "المستندات",
  "nav.recruitment": "التوظيف",
  "nav.kpi": "مؤشرات الأداء",
  "nav.reports": "التقارير",
  "nav.group.hr": "الموارد البشرية",
  "nav.group.ops": "العمليات",
  "nav.group.system": "النظام",
  "nav.signout": "تسجيل الخروج",
  "nav.profile": "الملف الشخصي",

  /* ====== Dashboard shared ====== */
  "dash.welcome": "مرحبًا بعودتك",
  "dash.search": "بحث…",
  "dash.search.placeholder": "ابحث بالاسم أو الرقم أو الهاتف…",
  "dash.filters": "تصفية",
  "dash.department": "القسم",
  "dash.status": "الحالة",
  "dash.type": "النوع",
  "dash.nationality": "الجنسية",
  "dash.month": "الشهر",
  "dash.period": "الفترة",
  "dash.all": "الكل",
  "dash.add": "إضافة",
  "dash.addNew": "إضافة جديد",
  "dash.edit": "تعديل",
  "dash.delete": "حذف",
  "dash.save": "حفظ",
  "dash.cancel": "إلغاء",
  "dash.confirm": "تأكيد",
  "dash.confirmDelete": "تأكيد الحذف",
  "dash.confirmDeleteMsg": "هل أنت متأكد من حذف هذا السجل؟ لا يمكن التراجع عن هذه العملية.",
  "dash.actions": "إجراءات",
  "dash.view": "عرض",
  "dash.export": "تصدير",
  "dash.import": "استيراد",
  "dash.loading": "جارٍ التحميل…",
  "dash.noData": "لا توجد بيانات",
  "dash.noDataDesc": "حاول تعديل عوامل التصفية أو إضافة سجل جديد.",
  "dash.error": "حدث خطأ ما",
  "dash.retry": "إعادة المحاولة",
  "dash.created": "تم الإنشاء بنجاح",
  "dash.updated": "تم التحديث بنجاح",
  "dash.deleted": "تم الحذف بنجاح",
  "dash.saved": "تم الحفظ بنجاح",
  "dash.approved": "تمت الموافقة على الإجازة",
  "dash.rejected": "تم رفض الإجازة",
  "dash.exported": "تم التصدير بنجاح",

  /* ====== Company overview page ====== */
  "company.title": "نظرة عامة على الشركة",
  "company.subtitle": "رؤى فورية لقوتك العاملة",
  "company.totalEmployees": "إجمالي الموظفين",
  "company.activeEmployees": "الموظفون النشطون",
  "company.saudization": "نسبة السعودة",
  "company.monthlyPayroll": "الرواتب الشهرية",
  "company.pendingLeaves": "الإجازات المعلقة",
  "company.avgKpi": "متوسط الأداء",
  "company.candidates": "المرشحون النشطون",
  "company.byDept": "الموظفون حسب القسم",
  "company.byVisa": "القوى العاملة حسب التأشيرة",
  "company.deptSalary": "متوسط الراتب حسب القسم",
  "company.payrollTrend": "اتجاه الرواتب (3 أشهر)",
  "company.profile": "ملف الشركة",
  "company.name": "مصنع تنور الجزيرة الصناعي",
  "company.address": "المدينة الصناعية، الدمام، المنطقة الشرقية، السعودية",
  "company.cr": "السجل التجاري",
  "company.vat": "الرقم الضريبي",
  "company.gosi": "مؤسسة التأمينات الاجتماعية",
  "company.established": "تأسس",
  "company.employees": "الموظفون",
  "company.departments": "الأقسام",

  /* ====== Employees page ====== */
  "emp.title": "الموظفون",
  "emp.subtitle": "إدارة سجلات القوى العاملة",
  "emp.cardView": "بطاقات",
  "emp.tableView": "جدول",
  "emp.empNo": "رقم الموظف",
  "emp.name": "الاسم الكامل",
  "emp.nameAr": "الاسم بالعربية",
  "emp.job": "المسمى الوظيفي",
  "emp.dept": "القسم",
  "emp.salary": "الراتب",
  "emp.contact": "التواصل",
  "emp.hireDate": "تاريخ التعيين",
  "emp.nationality": "الجنسية",
  "emp.gender": "الجنس",
  "emp.male": "ذكر",
  "emp.female": "أنثى",
  "emp.dob": "تاريخ الميلاد",
  "emp.marital": "الحالة الاجتماعية",
  "emp.married": "متزوج",
  "emp.single": "أعزب",
  "emp.divorced": "مطلق",
  "emp.widowed": "أرمل",
  "emp.phone": "الهاتف",
  "emp.email": "البريد الإلكتروني",
  "emp.address": "العنوان",
  "emp.emergency": "جهة اتصال الطوارئ",
  "emp.employmentType": "نوع التوظيف",
  "emp.fullTime": "دوام كامل",
  "emp.partTime": "دوام جزئي",
  "emp.contract": "نوع العقد",
  "emp.contractEnd": "نهاية العقد",
  "emp.basicSalary": "الراتب الأساسي",
  "emp.allowances": "البدلات",
  "emp.bank": "الحساب البنكي",
  "emp.iban": "آيبان",
  "emp.passport": "جواز السفر",
  "emp.passportNo": "رقم جواز السفر",
  "emp.passportExpiry": "انتهاء جواز السفر",
  "emp.iqama": "الإقامة",
  "emp.iqamaNo": "رقم الإقامة/الهوية",
  "emp.iqamaExpiry": "انتهاء الإقامة/الهوية",
  "emp.visa": "نوع التأشيرة",
  "emp.profilePhoto": "الصورة الشخصية",
  "emp.iqamaPhoto": "صورة الإقامة",
  "emp.passportPhoto": "صورة جواز السفر",
  "emp.notes": "ملاحظات",
  "emp.uploadPhoto": "رفع صورة",
  "emp.extractIqama": "استخراج من الإقامة",
  "emp.extractPassport": "استخراج من الجواز",
  "emp.extracting": "جارٍ الاستخراج…",
  "emp.extracted": "تم استخراج بيانات المستند",
  "emp.extractFailed": "تعذّر الاستخراج — يرجى التعبئة يدويًا",
  "emp.addEmployee": "إضافة موظف",
  "emp.editEmployee": "تعديل موظف",
  "emp.importCsv": "استيراد Excel",
  "emp.exportXlsx": "تصدير إلى Excel",
  "emp.total": "إجمالي الموظفين",
  "emp.active": "نشط",
  "emp.onLeave": "في إجازة",
  "emp.saudi": "السعوديون",
  "emp.viewDetails": "عرض التفاصيل",
  "emp.section.personal": "شخصي",
  "emp.section.employment": "وظيفي",
  "emp.section.legal": "المستندات القانونية",
  "emp.section.financial": "مالي",
  "emp.section.photos": "الصور والمستندات",

  /* ====== Attendance ====== */
  "att.title": "الحضور",
  "att.subtitle": "تتبع الحضور والانصراف اليومي",
  "att.date": "التاريخ",
  "att.checkIn": "وقت الحضور",
  "att.checkOut": "وقت الانصراف",
  "att.workHours": "ساعات العمل",
  "att.overtime": "ساعات إضافية",
  "att.present": "حاضر",
  "att.late": "متأخر",
  "att.absent": "غائب",
  "att.leave": "في إجازة",
  "att.holiday": "عطلة",
  "att.add": "إضافة سجل",
  "att.total": "إجمالي السجلات",
  "att.presentCount": "حاضرون",
  "att.lateCount": "تأخيرات",
  "att.leaveCount": "في إجازة",

  /* ====== Leave ====== */
  "leave.title": "إدارة الإجازات",
  "leave.subtitle": "الموافقة على إجازات الموظفين وتتبعها",
  "leave.type": "نوع الإجازة",
  "leave.annual": "سنوية",
  "leave.sick": "مرضية",
  "leave.emergency": "طارئة",
  "leave.unpaid": "بدون راتب",
  "leave.maternity": "أمومة",
  "leave.startDate": "تاريخ البداية",
  "leave.endDate": "تاريخ النهاية",
  "leave.days": "أيام",
  "leave.reason": "السبب",
  "leave.approver": "المعتمد",
  "leave.pending": "معلقة",
  "leave.approved": "موافق عليها",
  "leave.rejected": "مرفوضة",
  "leave.apply": "تقديم إجازة",
  "leave.approve": "موافقة",
  "leave.reject": "رفض",
  "leave.balance": "رصيد الإجازات",
  "leave.totalRequests": "إجمالي الطلبات",
  "leave.pendingBalance": "قيد المراجعة",
  "leave.approvedBalance": "أيام معتمدة",

  /* ====== Payroll ====== */
  "pay.title": "الرواتب",
  "pay.subtitle": "الرواتب والخصومات ومساهمات التأمينات",
  "pay.month": "الشهر",
  "pay.basic": "الراتب الأساسي",
  "pay.allowances": "البدلات",
  "pay.overtime": "الإضافي",
  "pay.deductions": "الخصومات",
  "pay.gosi": "التأمينات",
  "pay.net": "صافي الراتب",
  "pay.payDate": "تاريخ الدفع",
  "pay.run": "تشغيل الرواتب",
  "pay.runConfirm": "تشغيل رواتب {month}؟ سيتم استبدال السجلات الموجودة لهذا الشهر.",
  "pay.runSuccess": "تمت معالجة الرواتب لـ {month} ({count} موظفًا)",
  "pay.runLoading": "جارٍ معالجة الرواتب…",
  "pay.payslip": "قسيمة راتب",
  "pay.total": "إجمالي صافي الرواتب",
  "pay.totalGosi": "إجمالي التأمينات",
  "pay.totalOvertime": "إجمالي الإضافي",
  "pay.employees": "الموظفون المدفوع لهم",
  "pay.byMonth": "صافي الرواتب حسب الشهر",
  "pay.processed": "معالجة",
  "pay.paid": "مدفوعة",
  "pay.employee": "الموظف",
  "pay.gosiNote": "التأمينات: سعودي 9.75٪ · وافد 2٪",

  /* ====== Documents ====== */
  "doc.title": "المستندات",
  "doc.subtitle": "تتبع انتهاء المستندات القانونية والعقود",
  "doc.docType": "نوع المستند",
  "doc.iqama": "إقامة",
  "doc.passport": "جواز سفر",
  "doc.contract": "عقد",
  "doc.certificate": "شهادة",
  "doc.other": "أخرى",
  "doc.title2": "العنوان",
  "doc.issueDate": "تاريخ الإصدار",
  "doc.expiryDate": "تاريخ الانتهاء",
  "doc.file": "الملف",
  "doc.upload": "رفع مستند",
  "doc.add": "إضافة مستند",
  "doc.valid": "ساري",
  "doc.expiring": "ينتهي قريبًا",
  "doc.expired": "منتهي",
  "doc.total": "إجمالي المستندات",
  "doc.expiringSoon": "ينتهي (≤30 يومًا)",
  "doc.expiredCount": "منتهي",
  "doc.alertTitle": "تنبيهات الانتهاء",

  /* ====== Recruitment ====== */
  "rec.title": "التوظيف",
  "rec.subtitle": "تتبع المرشحين عبر مراحل التوظيف",
  "rec.position": "الوظيفة",
  "rec.source": "المصدر",
  "rec.experience": "الخبرة (سنوات)",
  "rec.rating": "التقييم",
  "rec.expectedSalary": "الراتب المتوقع",
  "rec.appliedAt": "تاريخ التقديم",
  "rec.add": "إضافة مرشح",
  "rec.applied": "تلقّي",
  "rec.screening": "فرز",
  "rec.interview": "مقابلة",
  "rec.offered": "عرض",
  "rec.hired": "توظيف",
  "rec.rejected": "مرفوض",
  "rec.total": "إجمالي المرشحين",
  "rec.inPipeline": "قيد المعالجة",
  "rec.interviewing": "في المقابلة",
  "rec.offeredCount": "عروض مقدمة",

  /* ====== KPI ====== */
  "kpi.title": "مؤشرات الأداء",
  "kpi.subtitle": "مقاييس الأداء لكل موظف",
  "kpi.productivity": "الإنتاجية",
  "kpi.quality": "الجودة",
  "kpi.teamwork": "العمل الجماعي",
  "kpi.punctuality": "الالتزام بالمواعيد",
  "kpi.initiative": "المبادرة",
  "kpi.finalScore": "الدرجة النهائية",
  "kpi.comments": "ملاحظات",
  "kpi.add": "إضافة تقييم",
  "kpi.edit": "تعديل التقييم",
  "kpi.distribution": "توزيع الدرجات",
  "kpi.avgScore": "متوسط الدرجة",
  "kpi.topCount": "أداء متميز (≥85)",
  "kpi.lowCount": "يحتاج تحسين (<70)",
  "kpi.total": "إجمالي التقييمات",
  "kpi.excellent": "ممتاز",
  "kpi.good": "جيد",
  "kpi.average": "متوسط",
  "kpi.poor": "ضعيف",

  /* ====== Reports ====== */
  "rep.title": "التقارير والتحليلات",
  "rep.subtitle": "تحليلات موارد بشرية متوافقة سعوديًا",
  "rep.saudization": "تقرير السعودة",
  "rep.saudi": "السعوديون",
  "rep.expat": "الوافدون",
  "rep.rate": "نسبة السعودة",
  "rep.target": "الهدف (نطاقات)",
  "rep.deptBreakdown": "تفصيل الأقسام",
  "rep.payrollByMonth": "الرواتب حسب الشهر",
  "rep.attendanceTrend": "الحضور (7 أيام)",
  "rep.kpiByDept": "متوسط الأداء حسب القسم",
  "rep.exportAllEmp": "تصدير كل الموظفين",
  "rep.exportFull": "تصدير التقرير الكامل",
  "rep.summary": "الملخص التنفيذي",

  /* ====== Footer ====== */
  "footer.rights": "جميع الحقوق محفوظة.",
  "footer.ai": "مساعد الذكاء الاصطناعي",
  "footer.poweredBy": "مدعوم من",

  /* ====== AI Assistant ====== */
  "ai.title": "مساعد الذكاء الاصطناعي",
  "ai.subtitle": "اسأل عن بيانات الموارد البشرية",
  "ai.placeholder": "اسأل أي شيء عن الموظفين أو الرواتب أو الإجازات…",
  "ai.send": "إرسال",
  "ai.thinking": "جارٍ التفكير…",
  "ai.welcome": "مرحبًا! أنا مساعد الموارد البشرية لديك. يمكنني الإجابة عن أسئلتك حول الموظفين والحضور والرواتب والإجازات والمستندات والتوظيف ومؤشرات الأداء. جرّب أن تسأل:\n• كم عدد الموظفين لدينا؟\n• ما هي نسبة السعودة لدينا؟\n• كم طلب إجازة معلّق؟",
  "ai.disclaimer": "الإجابات المُولّدة بالذكاء الاصطناعي تستخدم بيانات لحظية من قاعدة البيانات. تحقّق من القرارات الحرجة.",

  /* ====== Employee detail ====== */
  "det.profile": "الملف",
  "det.employment": "الوظيفة",
  "det.documents": "المستندات",
  "det.attendance": "الحضور",
  "det.leave": "الإجازات",
  "det.payroll": "الرواتب",
  "det.kpis": "الأداء",
  "det.personalInfo": "المعلومات الشخصية",
  "det.contactInfo": "معلومات التواصل",
  "det.employmentInfo": "المعلومات الوظيفية",
  "det.financialInfo": "المعلومات المالية",
  "det.legalDocs": "المستندات القانونية",
  "det.noRecords": "لا توجد سجلات",
  "det.totalSalary": "إجمالي الراتب",
  "det.years": "سنوات",
  "det.days": "أيام",
};

const dictionaries: Record<Locale, Dict> = { en, ar };

const STORAGE_KEY = "tanoor-locale";

type LanguageContextValue = {
  locale: Locale;
  dir: "ltr" | "rtl";
  t: (key: string, vars?: Record<string, string | number>) => string;
  toggle: () => void;
  setLocale: (l: Locale) => void;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

const listeners = new Set<() => void>();

function subscribe(cb: () => void) {
  listeners.add(cb);
  const onStorage = (e: StorageEvent) => {
    if (e.key === STORAGE_KEY) cb();
  };
  window.addEventListener("storage", onStorage);
  return () => {
    listeners.delete(cb);
    window.removeEventListener("storage", onStorage);
  };
}

function getSnapshot(): string {
  return window.localStorage.getItem(STORAGE_KEY) || "en";
}

function getServerSnapshot(): string {
  return "en";
}

function notify() {
  listeners.forEach((l) => l());
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const stored = useSyncExternalStore(
    subscribe,
    getSnapshot,
    getServerSnapshot,
  ) as Locale;

  const locale: Locale = stored === "ar" ? "ar" : "en";
  const dir: "ltr" | "rtl" = locale === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    const html = document.documentElement;
    html.lang = locale;
    html.dir = dir;
  }, [locale, dir]);

  const setLocale = useCallback((l: Locale) => {
    try {
      window.localStorage.setItem(STORAGE_KEY, l);
    } catch {
      /* ignore */
    }
    notify();
  }, []);

  const toggle = useCallback(() => {
    setLocale(stored === "ar" ? "en" : "ar");
  }, [stored, setLocale]);

  const t = useCallback(
    (key: string, vars?: Record<string, string | number>) => {
      let s = dictionaries[locale][key] ?? dictionaries.en[key] ?? key;
      if (vars) {
        for (const k of Object.keys(vars)) {
          s = s.replace(`{${k}}`, String(vars[k]));
        }
      }
      return s;
    },
    [locale],
  );

  const value = useMemo(
    () => ({ locale, dir, t, toggle, setLocale }),
    [locale, dir, t, toggle, setLocale],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return ctx;
}
